Administracyjne:
- code/modules/admin/**/*

Config:
- config/**/*

GitHub:
- .github/**/*

mapping:
- _maps/**/*

Dźwięk:
- sound/**/*

Grafika:
- icons/**/*.dmi

sql:
- SQL/**/*.sql

Narzędzia:
- tools/**/*

TGUI:
- tgui/**/*
