name: Add Extra PR labels

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for conflicting PRs
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "Konflikt"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "Ten Pull Request zawiera konflikty. Należy rozwiązać wszystkie konflikty przed merge."
      - name: Apply labels based on changed files
        if: github.event_name != 'push'
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/file_labeler.yml
